--- !ditz.rubyforge.org,2008-03-06/issue 
title: Improve DitzControl error handling
desc: |-
  DitzControl is not handling errors very well.
  Use ApplicationError (or DitzError) to show when running Ditz
  commands fails. Maybe that exception should be thrown
  all the way to the UI?
  Or should I get rid of Exceptions all together?
type: :task
component: ditz-gui
release: v0.1
reporter: Markus Silvan <markus.silvan@iki.fi>
status: :closed
disposition: :fixed
creation_time: 2014-10-12 13:21:05.857788 Z
references: []

id: 1d7244803305474ea207f8dc13467c8aff7b7437
log_events: 
- - 2014-10-12 13:21:07.601600 Z
  - Markus Silvan <markus.silvan@iki.fi>
  - created
  - ""
- - 2014-10-12 14:55:29.288669 Z
  - Markus Silvan <markus.silvan@iki.fi>
  - commented
  - |-
    Error handling improved on DitzControl side to
    raise DitzExceptions. Now make the GUI side
    react to them.
- - 2014-10-12 17:44:23.736442 Z
  - Markus Silvan <markus.silvan@iki.fi>
  - changed status from unstarted to in_progress
  - ""
- - 2014-10-14 11:57:32.099835 Z
  - Markus Silvan <markus.silvan@iki.fi>
  - commented
  - |-
    Verify that error handling works by "asking for" invalid Ditz items
    from the GUI with hardcoded ditz names or identifiers.
- - 2014-10-17 06:36:12.531187 Z
  - Markus Silvan <markus.silvan@iki.fi>
  - commented
  - |-
    "Error handling" as in "showing QMessageBox dialogs when
    DitzError is catched" has been verified to work nicely.
    Extend this functionality to all user actions.
- - 2014-10-17 07:49:48.505204 Z
  - Markus Silvan <markus.silvan@iki.fi>
  - commented
  - |-
    Try-excepts with QMessageBoxes are now added to all user actions.
    See if everything still works and then close this issue.
- - 2014-10-17 16:08:38.243750 Z
  - Markus Silvan <markus.silvan@iki.fi>
  - closed with disposition fixed
  - All good.
